apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-cip
  name: nginx-cip
  namespace: testing-space
spec:
  ports:
  - name: "30010"
    port: 30010
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP